### ISSUE TITLE
[Bug] xml.etree.ElementTree.ParseError: no element found

### ISSUE THREAD

**Issue by Kristinita** [math2001/SaneSnippets#1]
### 1. Summary

`sublime-snippet` files don't convert to `sane-snippet` for me.

### 2. Expected behavior

Successful conversion `sublime-snippet` to `sane-snippet`.

### 3. Actual behavior

```python
command: sane_snippets {"action": "migrate"}
Traceback (most recent call last):
  File "D:\Sublime Text Build 3126 x64 For Debug\sublime_plugin.py", line 780, in run_
    return self.run(**args)
  File "sane_snippets in D:\Sublime Text Build 3126 x64 For Debug\Data\Installed Packages\SaneSnippets.sublime-package", line 85, in run
  File "sane_snippets in D:\Sublime Text Build 3126 x64 For Debug\Data\Installed Packages\SaneSnippets.sublime-package", line 61, in migrate_action
  File "sane_snippets_tools in D:\Sublime Text Build 3126 x64 For Debug\Data\Installed Packages\SaneSnippets.sublime-package", line 86, in convert
  File "sane_snippets_tools in D:\Sublime Text Build 3126 x64 For Debug\Data\Installed Packages\SaneSnippets.sublime-package", line 50, in parse
  File "./python3.3/xml/etree/ElementTree.py", line 1242, in parse
  File "./python3.3/xml/etree/ElementTree.py", line 1730, in parse
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

### 4. Steps to reproduce

I reproduce the problem in fresh Sublime Text version without plugins and user settings.

I install your fork → I restart Sublime Text → `Preferences` → `Browse Packages…` → `User` → I create `snippets` folder → I create file `choco-zip.sublime-snippet` ([**on gist**](https://gist.github.com/Kristinita/6c14fa1c2570ef284b0c0a448ca6fae8)) → <kbd>Ctrl+Shift+P</kbd> → `SaneSnippets: Migrate` → I get stack trace, snippet don't convert for me to `sane-snippets`.

### 5. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126

Thanks.

**Comment by math2001** [comment]
Are you sure there is no empty `.sane-snippet`?
